name: CI

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  typecheck_scoped:
    name: Typecheck (scoped)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # SOLO type-check de lo nuevo (evita legacy)
      - name: Typecheck (tsconfig.ci.json)
        run: npx tsc -p tsconfig.ci.json --noEmit
