name: CI - Deploy Firebase Rules & Indexes

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build (sanity check)
        run: npm run build

      - name: Firebase deploy (rules & indexes only)
        uses: w9jds/firebase-action@v13
        with:
          args: deploy --only firestore:rules,firestore:indexes,storage:rules --project crm-sincro-v2
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
